apiVersion: v1
kind: ConfigMap
metadata:
  name: simulator-conf
data:
  env: |    
    KafkaReadTopic=route.new-direction
    KafkaProduceTopic=route.new-position
    KafkaConsumerGroupId=simulator
    KafkaBootstrapServers=
    security.protocol=
    sasl.mechanisms=
    sasl.username=
    sasl.password=